/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.RegistroBiblioteca;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Libro;

/**
 *
 * @author tallerespa
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        pnlAgregar.setVisible(false);
        pnlListar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnlAgregar = new javax.swing.JPanel();
        lblCodigoA = new javax.swing.JLabel();
        lblNombreA = new javax.swing.JLabel();
        lblFormatoTapaA = new javax.swing.JLabel();
        lblCantidadA = new javax.swing.JLabel();
        lblCategoriaA = new javax.swing.JLabel();
        lblAutorA = new javax.swing.JLabel();
        lblNuevoA = new javax.swing.JLabel();
        txtCodigoA = new javax.swing.JTextField();
        txtNombreA = new javax.swing.JTextField();
        rbtnDuraA = new javax.swing.JRadioButton();
        rbtnBlanda = new javax.swing.JRadioButton();
        txtCantidadA = new javax.swing.JTextField();
        cbxCategoriaA = new javax.swing.JComboBox<>();
        txtAutorA = new javax.swing.JTextField();
        chxNuevo = new javax.swing.JCheckBox();
        btnGuardarA = new javax.swing.JButton();
        btnSalirA = new javax.swing.JButton();
        btnLimpiarA = new javax.swing.JButton();
        pnlListar = new javax.swing.JPanel();
        lblBuscarL = new javax.swing.JLabel();
        txtBuscarL = new javax.swing.JTextField();
        btnBuscarL = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbListar = new javax.swing.JTable();
        btnEliminarL = new javax.swing.JButton();
        btnModificarL = new javax.swing.JButton();
        btnSalirL = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuAgregar = new javax.swing.JMenuItem();
        menuListar = new javax.swing.JMenuItem();
        menuSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCodigoA.setText("Codigo");

        lblNombreA.setText("Nombre");

        lblFormatoTapaA.setText("Formato tapa");

        lblCantidadA.setText("Cantidad de Paginas");

        lblCategoriaA.setText("Categoria");

        lblAutorA.setText("Autor");

        lblNuevoA.setText("Nuevo");

        buttonGroup1.add(rbtnDuraA);
        rbtnDuraA.setText("Dura");

        buttonGroup1.add(rbtnBlanda);
        rbtnBlanda.setText("Blanda");

        cbxCategoriaA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Accion", "Fantasia", "Novela", "Drama", "Educativo" }));

        btnGuardarA.setText("Guardar");
        btnGuardarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarAActionPerformed(evt);
            }
        });

        btnSalirA.setText("Salir");
        btnSalirA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirAActionPerformed(evt);
            }
        });

        btnLimpiarA.setText("Limpiar");
        btnLimpiarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAgregarLayout = new javax.swing.GroupLayout(pnlAgregar);
        pnlAgregar.setLayout(pnlAgregarLayout);
        pnlAgregarLayout.setHorizontalGroup(
            pnlAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAgregarLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(pnlAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCodigoA)
                    .addComponent(lblNombreA)
                    .addComponent(lblFormatoTapaA)
                    .addComponent(lblCantidadA)
                    .addComponent(lblCategoriaA)
                    .addComponent(lblAutorA)
                    .addComponent(lblNuevoA))
                .addGap(35, 35, 35)
                .addGroup(pnlAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAgregarLayout.createSequentialGroup()
                        .addComponent(chxNuevo)
                        .addContainerGap())
                    .addGroup(pnlAgregarLayout.createSequentialGroup()
                        .addGroup(pnlAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlAgregarLayout.createSequentialGroup()
                                .addComponent(rbtnDuraA)
                                .addGap(18, 18, 18)
                                .addComponent(rbtnBlanda))
                            .addComponent(txtCodigoA, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreA, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCantidadA)
                            .addComponent(cbxCategoriaA, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAutorA, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addGroup(pnlAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGuardarA, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSalirA, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnLimpiarA, javax.swing.GroupLayout.Alignment.TRAILING)))))
        );
        pnlAgregarLayout.setVerticalGroup(
            pnlAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAgregarLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(pnlAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigoA)
                    .addComponent(txtCodigoA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardarA))
                .addGap(18, 18, 18)
                .addGroup(pnlAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreA)
                    .addComponent(txtNombreA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiarA))
                .addGap(18, 18, 18)
                .addGroup(pnlAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFormatoTapaA)
                    .addComponent(rbtnDuraA)
                    .addComponent(rbtnBlanda)
                    .addComponent(btnSalirA))
                .addGap(18, 18, 18)
                .addGroup(pnlAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantidadA)
                    .addComponent(txtCantidadA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(pnlAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategoriaA)
                    .addComponent(cbxCategoriaA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(pnlAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAutorA)
                    .addComponent(txtAutorA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNuevoA)
                    .addComponent(chxNuevo))
                .addContainerGap(190, Short.MAX_VALUE))
        );

        lblBuscarL.setText("Buscar Por Codigo");

        btnBuscarL.setText("Buscar");
        btnBuscarL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarLActionPerformed(evt);
            }
        });

        tbListar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Formato", "Paginas", "Categoria", "Autor", "Nuevo"
            }
        ));
        jScrollPane1.setViewportView(tbListar);

        btnEliminarL.setText("Eliminar");
        btnEliminarL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarLActionPerformed(evt);
            }
        });

        btnModificarL.setText("Modificar");
        btnModificarL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarLActionPerformed(evt);
            }
        });

        btnSalirL.setText("Salir");
        btnSalirL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlListarLayout = new javax.swing.GroupLayout(pnlListar);
        pnlListar.setLayout(pnlListarLayout);
        pnlListarLayout.setHorizontalGroup(
            pnlListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListarLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(pnlListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlListarLayout.createSequentialGroup()
                        .addComponent(btnEliminarL)
                        .addGap(41, 41, 41)
                        .addComponent(btnModificarL)
                        .addGap(38, 38, 38)
                        .addComponent(btnSalirL)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlListarLayout.createSequentialGroup()
                        .addComponent(txtBuscarL, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuscarL)
                        .addGap(43, 43, 43))
                    .addGroup(pnlListarLayout.createSequentialGroup()
                        .addGroup(pnlListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBuscarL)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(51, Short.MAX_VALUE))))
        );
        pnlListarLayout.setVerticalGroup(
            pnlListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListarLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblBuscarL)
                .addGap(18, 18, 18)
                .addGroup(pnlListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarL))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(pnlListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarL)
                    .addComponent(btnModificarL)
                    .addComponent(btnSalirL))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jMenu1.setText("Procesos");

        menuAgregar.setText("Agregar");
        menuAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAgregarActionPerformed(evt);
            }
        });
        jMenu1.add(menuAgregar);

        menuListar.setText("Listar");
        menuListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuListarActionPerformed(evt);
            }
        });
        jMenu1.add(menuListar);

        menuSalir.setText("Salir");
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });
        jMenu1.add(menuSalir);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(pnlAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlListar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlListar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 206, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarAActionPerformed
        // TODO add your handling code here:
        try {
            RegistroBiblioteca registro = new RegistroBiblioteca();
            Libro libro = new Libro(txtCodigoA.getText(),
                    txtNombreA.getText(),
                    rbtnBlanda.isSelected() ? "D" : "B",
                    Integer.parseInt(txtCantidadA.getText()),
                    cbxCategoriaA.getSelectedItem().toString(),
                    txtAutorA.getText(),
                    chxNuevo.isSelected());

            if (registro.agregar(libro) == 1) {
                JOptionPane.showMessageDialog(this, "Se agrego");
                limpiar();
            } else {
                JOptionPane.showMessageDialog(this, "No agrego");
            }
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Problemas con el driver de conecion");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Problema sql " + ex.getMessage());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex);

        }

    }//GEN-LAST:event_btnGuardarAActionPerformed

    private void btnLimpiarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarAActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_btnLimpiarAActionPerformed

    private void btnModificarLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarLActionPerformed
        // TODO add your handling code here:
       try {
            RegistroBiblioteca registro = new RegistroBiblioteca();
            String busqueda = txtBuscarL.getText();

            if (registro.buscar(busqueda) != null) {
                JOptionPane.showMessageDialog(this, " se encontro : \n" + registro.buscar(busqueda).toString());

                txtCodigoA.setText(registro.buscar(busqueda).getCodigo());
                txtNombreA.setText(registro.buscar(busqueda).getNombre());
                txtCantidadA.setText(registro.buscar(busqueda).getPaginas() + "");
                if (registro.buscar(busqueda).getFormato().equals("B")) {
                    rbtnBlanda.setSelected(true);
                } else {
                    rbtnDuraA.setSelected(true);
                }

                cbxCategoriaA.setSelectedItem(registro.buscar(busqueda).getCategoria());
                txtAutorA.setText(registro.buscar(busqueda).getAutor());

                chxNuevo.setSelected(registro.buscar(busqueda).isNuevo());
                txtCodigoA.setEnabled(false);
                pnlListar.setVisible(false);
                pnlAgregar.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "No se encontro");
            }
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Problemas con el driver de conecion");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Problema sql " + ex.getMessage());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }//GEN-LAST:event_btnModificarLActionPerformed

    private void btnBuscarLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarLActionPerformed
        // TODO add your handling code here:
        try {
            RegistroBiblioteca registro = new RegistroBiblioteca();
            String busqueda = txtBuscarL.getText();

            if (registro.buscar(busqueda) != null) {
                JOptionPane.showMessageDialog(this, "se encontro");

                DefaultTableModel modelo = new DefaultTableModel();
                modelo.setColumnIdentifiers(
                        new Object[]{"Codigo", "Nombre", "Formato",
                            "Paginas", "Categoria", "Autor", "Nuevo"});
                modelo.addRow( 
                        new Object[]{registro.buscar(busqueda).getCodigo(),
                            registro.buscar(busqueda).getNombre(),
                            registro.buscar(busqueda).getFormato(),
                            registro.buscar(busqueda).getPaginas(),
                            registro.buscar(busqueda).getCategoria(),
                            registro.buscar(busqueda).getAutor(),
                            registro.buscar(busqueda).isNuevo(),
                            });
                tbListar.setModel(modelo);
            } else {
                JOptionPane.showMessageDialog(this, "No Encontro Nada :(");
            }
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Problemas con el driver de conecion");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Problema sql " + ex.getMessage());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
        
    }//GEN-LAST:event_btnBuscarLActionPerformed

    private void btnEliminarLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarLActionPerformed
        // TODO add your handling code here:
        try {
              RegistroBiblioteca registro = new RegistroBiblioteca();
            DefaultTableModel modelotabla = (DefaultTableModel) tbListar.getModel();

            String codigo = (String) modelotabla.getValueAt(tbListar.getSelectedRow(), 0);
            String nombre = (String) modelotabla.getValueAt(tbListar.getSelectedRow(), 1);
            String formato = (String) modelotabla.getValueAt(tbListar.getSelectedRow(), 2);
            int paginas = (int) modelotabla.getValueAt(tbListar.getSelectedRow(), 3);
            String categoria = (String) modelotabla.getValueAt(tbListar.getSelectedRow(), 4);
            String autor = (String) modelotabla.getValueAt(tbListar.getSelectedRow(), 5);
            boolean nuevo = (boolean) modelotabla.getValueAt(tbListar.getSelectedRow(), 6);
            Libro libro= new Libro(codigo,nombre,formato,paginas,categoria,autor,nuevo);
            if (registro.eliminar(codigo) == 1) {
                JOptionPane.showMessageDialog(this, "Se Elimino");
            } else {
                JOptionPane.showMessageDialog(this, "No Elimino");
            }
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Problemas con el driver de conecion");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Problema sql " + ex.getMessage());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }//GEN-LAST:event_btnEliminarLActionPerformed

    private void menuListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuListarActionPerformed
        // TODO add your handling code here:
        pnlAgregar.setVisible(false);
        pnlListar.setVisible(true);
        txtCodigoA.setEnabled(true);
        try {
            RegistroBiblioteca registro = new RegistroBiblioteca();
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.setColumnIdentifiers(
                    new Object[]{"Codigo", "Nombre", "Formato",
                        "Paginas", "Categoria", "Autor", "Nuevo"});
            for (Libro tmp : registro.mostrar()) {
                modelo.addRow(
                        new Object[]{tmp.getCodigo(),
                            tmp.getNombre(),
                            tmp.getFormato(),
                            tmp.getPaginas(),
                            tmp.getCategoria(),
                            tmp.getAutor(),
                            tmp.isNuevo()
                        });

            }
            tbListar.setModel(modelo);
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Problemas con el driver de conecion");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Problema sql " + ex.getMessage());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }//GEN-LAST:event_menuListarActionPerformed

    private void menuAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAgregarActionPerformed
        // TODO add your handling code here:
        pnlAgregar.setVisible(true);
        pnlListar.setVisible(false);
        txtCodigoA.setEnabled(true);
        limpiar();
    }//GEN-LAST:event_menuAgregarActionPerformed

    private void btnSalirAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirAActionPerformed
        // TODO add your handling code here:

        System.exit(1);
    }//GEN-LAST:event_btnSalirAActionPerformed

    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
        // TODO add your handling code here:
        System.exit(1);

    }//GEN-LAST:event_menuSalirActionPerformed

    private void btnSalirLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirLActionPerformed
        // TODO add your handling code here:
        System.exit(1);
    }//GEN-LAST:event_btnSalirLActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    private void limpiar() {

        txtCodigoA.setText("");
        txtNombreA.setText("");
        txtCantidadA.setText("");
        buttonGroup1.clearSelection();
        cbxCategoriaA.setSelectedIndex(0);
        chxNuevo.setSelected(false);
        txtAutorA.setText("");
        txtBuscarL.setText("");
        txtCodigoA.setEnabled(true);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarL;
    private javax.swing.JButton btnEliminarL;
    private javax.swing.JButton btnGuardarA;
    private javax.swing.JButton btnLimpiarA;
    private javax.swing.JButton btnModificarL;
    private javax.swing.JButton btnSalirA;
    private javax.swing.JButton btnSalirL;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbxCategoriaA;
    private javax.swing.JCheckBox chxNuevo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAutorA;
    private javax.swing.JLabel lblBuscarL;
    private javax.swing.JLabel lblCantidadA;
    private javax.swing.JLabel lblCategoriaA;
    private javax.swing.JLabel lblCodigoA;
    private javax.swing.JLabel lblFormatoTapaA;
    private javax.swing.JLabel lblNombreA;
    private javax.swing.JLabel lblNuevoA;
    private javax.swing.JMenuItem menuAgregar;
    private javax.swing.JMenuItem menuListar;
    private javax.swing.JMenuItem menuSalir;
    private javax.swing.JPanel pnlAgregar;
    private javax.swing.JPanel pnlListar;
    private javax.swing.JRadioButton rbtnBlanda;
    private javax.swing.JRadioButton rbtnDuraA;
    private javax.swing.JTable tbListar;
    private javax.swing.JTextField txtAutorA;
    private javax.swing.JTextField txtBuscarL;
    private javax.swing.JTextField txtCantidadA;
    private javax.swing.JTextField txtCodigoA;
    private javax.swing.JTextField txtNombreA;
    // End of variables declaration//GEN-END:variables
}
